### PR TITLE
Fix sample.csv dates

### LINKED ISSUE #11: [Bug] Sample data not showing data?
hunter config
```
tests:
  local1:
    type: csv
    file: tests/resources/sample.csv
    time_column: time
    metrics: [metric1, metric2]
    attributes: [commit]

  local2:
    type: csv
    file: tests/resources/sample.csv
    time_column: time
    metrics:
      m1:
        column: metric1
        direction: 1
      m2:
        column: metric2
        direction: -1
    attributes: [ commit ]

test_groups:
  local:
    - local1
    - local2
```

the sample.csv is the same as what is here : https://github.com/datastax-labs/hunter/blob/master/tests/resources/sample.csv 

When I run `hunter validate`
```
jtaleric at polaris in ~/code/hunter on master $ hunter validate
INFO: Checking local1
WARNING: Test's metric does not have data: local1 metric1
WARNING: Test's metric does not have data: local1 metric2
INFO: Checking local2
WARNING: Test's metric does not have data: local2 m1
WARNING: Test's metric does not have data: local2 m2
INFO: Validation finished: VALID
```

We can see the mention of test metric does not have data... 
```
jtaleric at polaris in ~/code/hunter on master $ hunter analyze local1
INFO: Computing change points for test local1...
time    commit    metric1    metric2
------  --------  ---------  ---------
```

### PR DESCRIPTION
**Pull request by jtaleric**
Update the dates so the test samples works

closes #11

### CODE REVIEW

**Comment by jtaleric** [comment]
@henrikingo / @pkolaczk hey! no rush but I figure I would tag yall since I cannot assign anyone to review.

**Comment by jtaleric** [comment]
@smccarthy788 -- Trying one more person :D

**Comment by henrikingo** [comment]
I no longer have admin access...

**Comment by smccarthy788** [comment]
Some tests need to be updated, otherwise +1.

**Comment by jtaleric** [comment]
> Some tests need to be updated, otherwise +1.

sup @smccarthy788 I tried running the tests locally, but ran into some odd python package issues. 

```
Traceback (most recent call last):
  File "/home/jtaleric/code/hunter/build/wrappers/bin/poetry", line 5, in <module>
    from poetry.console import main
  File "/home/jtaleric/code/hunter/build/venvs/poetry/lib64/python3.12/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/jtaleric/code/hunter/build/venvs/poetry/lib64/python3.12/site-packages/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/home/jtaleric/code/hunter/build/venvs/poetry/lib64/python3.12/site-packages/poetry/console/commands/__init__.py", line 2, in <module>
    from .add import AddCommand
  File "/home/jtaleric/code/hunter/build/venvs/poetry/lib64/python3.12/site-packages/poetry/console/commands/add.py", line 8, in <module>
    from .init import InitCommand
  File "/home/jtaleric/code/hunter/build/venvs/poetry/lib64/python3.12/site-packages/poetry/console/commands/init.py", line 16, in <module>
    from poetry.core.pyproject import PyProjectException
  File "/home/jtaleric/code/hunter/build/venvs/poetry/lib64/python3.12/site-packages/poetry/core/pyproject/__init__.py", line 2, in <module>
    from poetry.core.pyproject.tables import BuildSystem
  File "/home/jtaleric/code/hunter/build/venvs/poetry/lib64/python3.12/site-packages/poetry/core/pyproject/tables.py", line 5, in <module>
    from poetry.core.utils._compat import Path
  File "/home/jtaleric/code/hunter/build/venvs/poetry/lib64/python3.12/site-packages/poetry/core/utils/_compat.py", line 8, in <module>
    import six.moves.urllib.parse as urllib_parse
```

Anyway, might be a separate issue. I am unable to trigger the Action to run, so I need someone to bless the run! :D

**Review by smccarthy788 — APPROVED** [review]
tyvm!

**Pull request merged**
